// Английский перевод. Ключ — русская строка из самой игры (js/core/lang.js).
//
// Порядок и разбиение по разделам такие же, как в игре: приборы, меню,
// экраны, карта, сообщения. Так проще искать и видно, что ничего не
// потеряно. Проверка следит, чтобы каждая русская строка из игровых
// файлов здесь была (tools/test.mjs).
//
// Регистр переносится: где в игре капслок прибора, там он и в переводе.

export const EN = {
  // --- единицы и числа -------------------------------------------------------
  ' м': ' m',
  ' км': ' km',
  ' млн км': ' M km',
  ' м/с': ' m/s',
  ' м/с²': ' m/s²',
  ' км/с': ' km/s',
  ' тыс. км/с': ' k km/s',
  ' с': ' s',
  ' С': ' S',
  ' мин': ' min',
  ' мин ': ' min ',
  ' ч ': ' h ',
  ' мс': ' ms',
  '— мс': '— ms',
  ' СВЕТОВЫХ ЛЕТ': ' LIGHT YEARS',
  'с.ш.': 'N',
  'ю.ш.': 'S',

  // --- приборы полёта --------------------------------------------------------
  'СКОРОСТЬ': 'SPEED',
  'ВЫСОТА': 'ALTITUDE',
  'ВЕРТ': 'VERT',
  'БОК': 'LAT',
  'ДО ЦЕЛИ': 'TO TARGET',
  'ТЯГА': 'THRUST',
  'ТЯГА НАЗАД': 'REVERSE',
  'ФОРСАЖ': 'BOOST',
  'КОРПУС': 'HULL',
  'ЩИТ': 'SHIELD',
  'ШАССИ': 'GEAR',
  'ГОТОВО': 'READY',
  'ГОТОВ': 'READY',
  'УБРАНО': 'STOWED',
  'ВЫПУЩЕНО': 'DOWN',
  'ВЫХОД': 'EXTENDING',
  'ЦЕЛЬ': 'TARGET',
  'ДИСТ': 'DIST',
  'ДИСТ  ': 'DIST  ',
  'ПРИВОД': 'DRIVE',
  'ДВИГАТЕЛЬ': 'ENGINE',
  'СИСТЕМЫ': 'SYSTEMS',
  'РЕЖИМ': 'MODE',
  'СВОБОДНЫЙ': 'FREE',
  'ЗАХВАТ': 'CAPTURE',
  'ЗАХВАТ · ': 'CAPTURE · ',
  'ТЯЖЕСТЬ': 'GRAVITY',
  'у грунта ': 'at surface ',
  'СКАНЕР ': 'SCANNER ',
  'ДАЛЬНОСТЬ ': 'RANGE ',
  'ЛОКАТОР': 'SCOPE',
  'ЛОКАТОР · ПИЛОТОВ РЯДОМ ': 'SCOPE · PILOTS NEARBY ',
  'ПИЛОТОВ РЯДОМ ': 'PILOTS NEARBY ',
  'ПИЛОТ': 'PILOT',
  'СВЯЗЬ': 'LINK',
  'канал чист': 'channel clear',
  'БЕЗ УПРАВЛЕНИЯ': 'NO CONTROL',
  'ДЕРЖИТЕСЬ': 'BRACE',
  'TAB — ВЫБРАТЬ ЦЕЛЬ': 'TAB — SELECT TARGET',

  // --- привод, варп, прыжок --------------------------------------------------
  'КАЛИБРОВКА': 'CALIBRATING',
  'НАВЕДИСЬ': 'AIM',
  'НАВЕДИСЬ НА ЦЕЛЬ': 'AIM AT TARGET',
  'ВЕДЁТ': 'GUIDING',
  'ПРЫЖОК': 'JUMP',
  'ГАШЕНИЕ': 'SLOWING',
  'КВАНТОВЫЙ ПРЫЖОК · ': 'QUANTUM JUMP · ',
  'B — СОРВАТЬ ПРЫЖОК': 'B — ABORT JUMP',
  'ВАРП': 'WARP',
  'ВАРП · ': 'WARP · ',
  'ВАРП: РАСКРУТКА': 'WARP: SPOOLING',
  'ВАРП: СОВМЕСТИ НОС С ОТМЕТКОЙ · МИМО ': 'WARP: PUT NOSE ON MARKER · OFF BY ',
  'СИСТЕМА ЗАГРУЖЕНА': 'SYSTEM LOADED',
  'ВЫГРУЗКА СИСТЕМЫ': 'UNLOADING SYSTEM',

  // --- стыковка и посадка ----------------------------------------------------
  'ДОКИНГ': 'DOCKING',
  'СТВОР ПОРТА  ': 'PORT SLOT  ',
  'ОСЬ': 'AXIS',
  'КРЕН': 'ROLL',
  'СКОР': 'SPD',
  'ПОСАДКА': 'LANDING',
  'ГОТОВ К ПОСАДКЕ': 'READY TO LAND',
  'НАКЛОН': 'TILT',
  'УКЛОН': 'SLOPE',
  'ОТРЫВ': 'LIFTING',
  'ВЗЛЁТ': 'LIFT OFF',
  ' с — ВЗЛЁТ': ' s — LIFT OFF',
  'УДЕРЖАТЬ ПРОБЕЛ ': 'HOLD SPACE ',
  'ДЕРЖАТЬ ЕЩЁ ': 'HOLD FOR ',
  'ПРОБЕЛ — ЗАФИКСИРОВАТЬ · УДЕРЖАТЬ — ВЗЛЁТ': 'SPACE — SECURE · HOLD — LIFT OFF',
  'НА ГРУНТЕ · ДВИГАТЕЛИ ОТКЛЮЧЕНЫ': 'ON GROUND · ENGINES OFF',
  '° · ПЛОЩАДКА ': '° · PAD ',
  ' · ПОСАДОК ': ' · LANDINGS ',

  // --- связь -----------------------------------------------------------------
  'АВТОНОМНО': 'OFFLINE',
  'БЕЗ СЕТИ': 'NO NETWORK',
  'СОЕДИНЕНИЕ': 'CONNECTING',
  'СВЯЗЬ ОБОРВАНА': 'LINK LOST',
  '  ПОТЕРИ ': '  LOSS ',

  // --- карта и меню пилота -------------------------------------------------------
  'ОБЪЕКТ НЕ ВЫБРАН': 'NO OBJECT SELECTED',
  'ЦЕЛЬ ВАРПА: ': 'WARP TARGET: ',
  ' СВ. ЛЕТ · ': ' LY · ',
  'СИСТЕМА НЕ ВЫБРАНА': 'NO SYSTEM SELECTED',
  ' · J В ПОЛЁТЕ': ' · J IN FLIGHT',
  'КАРТА ГАЛАКТИКИ': 'GALAXY MAP',
  'ВЫ В СИСТЕМЕ ': 'YOU ARE IN ',
  '←,→ / ЛКМ — ВЫБРАТЬ СИСТЕМУ (ОНА СРАЗУ СТАНОВИТСЯ ЦЕЛЬЮ ВАРПА)': '←,→ / LMB — SELECT SYSTEM (IT BECOMES THE WARP TARGET AT ONCE)',
  'G — НАЗАД К СИСТЕМЕ · M — ЗАКРЫТЬ · ПРЫЖОК — J В ПОЛЁТЕ': 'G — BACK TO SYSTEM · M — CLOSE · JUMP — J IN FLIGHT',
  ' · КЛАСС ': ' · CLASS ',
  'Температура': 'Temperature',
  'Светимость': 'Luminosity',
  ' солнечной': ' solar',
  'Обитаемая зона': 'Habitable zone',
  ' тыс. км': ' k km',
  'Расстояние': 'Distance',
  '— вы здесь': '— you are here',
  ' св. лет': ' ly',
  'Прыжок': 'Jump',
  ' секунд': ' seconds',
  'Текущая система. Её карта — на клавише G.': 'Current system. Its map is on G.',
  'Что там внутри, известно только по прибытии: система собирается ': 'What is inside is known only on arrival: the system is built ',
  'под тоннелем прыжка.': 'under the jump tunnel.',
  'ЦЕЛЬ ВАРПА · J В ПОЛЁТЕ': 'WARP TARGET · J IN FLIGHT',
  ' Земли': ' Earths',
  ' Луны': ' Moons',
  ' кг · ': ' kg · ',
  'год': 'year',
  'года': 'years',
  'лет': 'years',
  ' К (': ' K (',
  'исключена': 'excluded',
  'поверхности нет': 'no surface',
  'нужен аэродинамический спуск': 'aerodynamic descent required',
  'возможна: шасси и R/F': 'possible: gear and R/F',
  'ДО КОРАБЛЯ': 'TO SHIP',
  'Точка в пустоте, к которой можно прыгнуть. Нужна, когда ': 'A point in empty space you can jump to. Needed when ',
  'прямой коридор до цели перекрыт телом, над которым висишь: сначала ': 'the direct corridor is blocked by the body you hover over: first ',
  'прыжок сюда, потом к цели.': 'jump here, then to the target.',
  'ТЕЛО': 'BODY',
  'УДАЛЕНИЕ': 'DISTANCE',
  ' радиуса)': ' radii)',
  'Орбитальный порт: единственное место, где восстанавливают ': 'Orbital port: the only place where a hull is ',
  'корпус. Створ смотрит от планеты, барабан вращается — крен на входе ': 'repaired. The slot faces away from the planet, the drum spins — match ',
  'согласуют с ним.': 'your roll to it on entry.',
  'ПЛАНЕТА': 'PLANET',
  'ВЫСОТА ОРБИТЫ': 'ORBIT ALTITUDE',
  'ОБОРОТ ВОКРУГ': 'ORBITS',
  'ВРАЩЕНИЕ': 'ROTATION',
  'оборот за ': 'one turn in ',
  'СТЫКОВКА': 'DOCKING',
  'скорость до ': 'speed up to ',
  'РАДИУС': 'RADIUS',
  'МАССА': 'MASS',
  'ПЛОТНОСТЬ': 'DENSITY',
  ' г/см³': ' g/cm³',
  ' м/с² (': ' m/s² (',
  'ВТОРАЯ КОСМ.': 'ESCAPE VEL.',
  'ТЕМПЕРАТУРА': 'TEMPERATURE',
  'СУТКИ': 'DAY',
  'ОРБИТА': 'ORBIT',
  ' вокруг ': ' around ',
  'светила': 'the star',
  'ГОД': 'YEAR',
  'ОТ СВЕТИЛА': 'FROM STAR',
  ' радиусов)': ' radii)',
  'АТМОСФЕРА': 'ATMOSPHERE',
  ' бар, до ': ' bar, up to ',
  'СОСТАВ': 'COMPOSITION',
  'нет': 'no',
  'КОЛЬЦА': 'RINGS',
  'есть': 'yes',
  'СТАНЦИЯ': 'STATION',
  'ЛУНЫ': 'MOONS',
  'КОРИДОР': 'CORRIDOR',
  'свободен — B': 'clear — B',
  'КАРТА СИСТЕМЫ ': 'SYSTEM MAP ',
  'МАСШТАБ ×': 'SCALE ×',
  '   ЗА ': '   FOLLOWING ',
  'КОЛЕСО / W,S — МАСШТАБ · ЛКМ — ВЫБОР · ТЯНУТЬ — СДВИГ': 'WHEEL / W,S — ZOOM · LMB — SELECT · DRAG — PAN',
  '←,→ — ПО ОБЪЕКТАМ · ПРОБЕЛ — К ВЫБРАННОМУ · TAB — НАЗНАЧИТЬ ЦЕЛЬЮ · ': '←,→ — CYCLE OBJECTS · SPACE — GO TO SELECTED · TAB — SET AS TARGET · ',
  'X — СБРОС · M — ЗАКРЫТЬ': 'X — RESET · M — CLOSE',
  'G — КАРТА ГАЛАКТИКИ': 'G — GALAXY MAP',
  'КОРАБЛЬ': 'SHIP',
  'Объект не выбран. Ткни в планету, станцию или луну — ': 'No object selected. Click a planet, station or moon — ',
  'здесь будет всё, что о ней известно.': 'everything known about it will appear here.',
  '● ТЕКУЩАЯ ЦЕЛЬ': '● CURRENT TARGET',
  'TAB — НАЗНАЧИТЬ ЦЕЛЬЮ': 'TAB — SET AS TARGET',
  'ГРУЗ': 'CARGO',
  'ЗАДАНИЯ': 'CONTRACTS',
  'ФИНАНСЫ': 'FINANCES',
  'ЛЁГКИЙ ТОРГОВЫЙ КОРАБЛЬ': 'LIGHT TRADER',
  'ГАБАРИТЫ': 'DIMENSIONS',
  'ДЛИНА': 'LENGTH',
  'ШИРИНА': 'WIDTH',
  'СОСТОЯНИЕ': 'CONDITION',
  'НЕ УСТАНОВЛЕНЫ': 'NOT INSTALLED',
  'ТОПЛИВО': 'FUEL',
  'ХАРАКТЕРИСТИКИ': 'PERFORMANCE',
  'ПРЕДЕЛ ХОДА': 'TOP SPEED',
  'НА ФОРСАЖЕ': 'ON BOOST',
  'РАЗГОН': 'ACCELERATION',
  'ТОРМОЖЕНИЕ': 'BRAKING',
  'ПОПЕРЁК КУРСА': 'LATERAL',
  'УСТАНОВЛЕННЫЕ МОДУЛИ': 'INSTALLED MODULES',
  'ЗАНЯТО ': 'USED ',
  ' Т': ' T',
  'СВОБОДНО ': 'FREE ',
  'ТРЮМ ПУСТ': 'HOLD EMPTY',
  'НАИМЕНОВАНИЕ': 'NAME',
  'АКТИВНЫХ ЗАДАНИЙ НЕТ': 'NO ACTIVE CONTRACTS',
  'БРАТЬ ИХ БУДЕТ ГДЕ НА СТАНЦИЯХ': 'THEY WILL BE TAKEN AT STATIONS',
  'СРОК ВЫШЕЛ': 'TIME UP',
  'ОСТАЛОСЬ ': 'LEFT ',
  'ПРОСРОЧЕНО': 'OVERDUE',
  'ПРИШЛО ': 'IN ',
  'УШЛО −': 'OUT −',
  'ВРЕМЯ': 'TIME',
  'ОПЕРАЦИЯ': 'OPERATION',
  'СУММА': 'AMOUNT',
  '…ещё ': '…and ',
  ' записей выше': ' more entries above',
  'ДВИЖЕНИЯ СРЕДСТВ НЕ БЫЛО': 'NO MONEY MOVED YET',
  'МЕНЮ ПИЛОТА · ': 'PILOT MENU · ',
  'МЕНЮ ПИЛОТА · АВТОНОМНО': 'PILOT MENU · OFFLINE',
  'МЕНЮ ПИЛОТА': 'PILOT MENU',
  '1–4 РАЗДЕЛ · I ЗАКРЫТЬ': '1–4 SECTION · I CLOSE',
  'КОРАБЛЬ В ПОЛЁТЕ · ': 'SHIP IN FLIGHT ·',

  // --- сообщения, модули корабля, каталог мира -----------------------------------
  'WebGL2 недоступен (': 'WebGL2 unavailable (',
  '), рисуем на Canvas 2D': '), drawing on Canvas 2D',
  'СТЫКОВОЧНЫЙ СБОР · ': 'DOCKING FEE · ',
  ' кр': ' cr',
  'РЕМОНТ КОРПУСА · −': 'HULL REPAIR · −',
  'РЕМОНТ: ': 'REPAIR: ',
  'ВЫЛЕТ РАЗРЕШЁН. УДАЧНОГО ПОЛЁТА.': 'LAUNCH CLEARED. GOOD FLIGHT.',
  'КОРАБЛЬ ЗАФИКСИРОВАН. ДВИГАТЕЛИ ОТКЛЮЧЕНЫ.': 'SHIP SECURED. ENGINES OFF.',
  'ОТРЫВ. ШАССИ ВЫПУЩЕНО — УБРАТЬ КЛАВИШЕЙ G.': 'LIFTED OFF. GEAR DOWN — RETRACT WITH G.',
  'НОВАЯ ИГРА': 'NEW GAME',
  'ЦЕЛЬ НЕ ВЫБРАНА': 'NO TARGET SELECTED',
  'ТЕЛЕПОРТ: ': 'TELEPORT: ',
  ', 6 км до порта': ', 6 km to port',
  ', высота ': ', altitude ',
  'ЩИТ ДЕРЖИТ · ': 'SHIELD HOLDS · ',
  'ПОПАДАНИЕ · КОРПУС ': 'HIT · HULL ',
  'ЦЕЛЬ УНИЧТОЖЕНА': 'TARGET DESTROYED',
  'ГДЕ-ТО РЯДОМ УНИЧТОЖЕН КОРАБЛЬ': 'A SHIP WAS DESTROYED NEARBY',
  'КОРАБЛЬ УНИЧТОЖЕН · ': 'SHIP DESTROYED · ',
  'Корабль уничтожен в бою.': 'Ship destroyed in combat.',
  'КОРАБЛЬ ВОССТАНОВЛЕН В ПОРТУ': 'SHIP RESTORED AT PORT',
  'SHIFT+N ЕЩЁ РАЗ — НАЧАТЬ ЗАНОВО': 'SHIFT+N AGAIN — START OVER',
  'ЗВУК ВКЛЮЧЁН': 'SOUND ON',
  'ЗВУК ВЫКЛЮЧЕН': 'SOUND OFF',
  'ГРОМКОСТЬ ': 'VOLUME ',
  'НАВЕДИ НОС НА ЦЕЛЬ': 'PUT THE NOSE ON A TARGET',
  'ЦЕЛЬ: ': 'TARGET: ',
  'ПРЫЖОК СОРВАН — ГАШЕНИЕ ХОДА': 'JUMP ABORTED — SLOWING DOWN',
  'ПРИВОД ОТКЛЮЧЁН': 'DRIVE OFF',
  'ОБХОД ЧЕРЕЗ ': 'DETOUR VIA ',
  ' — B ЕЩЁ РАЗ': ' — B AGAIN',
  'ПРИВОД: КАЛИБРОВКА НА ': 'DRIVE: CALIBRATING ON ',
  'ВАРП НЕ ПРЕРЫВАЕТСЯ': 'WARP CANNOT BE INTERRUPTED',
  'ВАРП ОТКЛЮЧЁН': 'WARP OFF',
  'ВАРП: ЦЕНТРОВКА НА ': 'WARP: ALIGNING ON ',
  'ШАССИ: ВЫПУСК': 'GEAR: EXTENDING',
  'ШАССИ: УБОРКА': 'GEAR: RETRACTING',
  'ПОСАДОЧНЫЙ КОМПЬЮТЕР ОТКЛЮЧЁН': 'LANDING COMPUTER OFF',
  'РЯДОМ НЕТ ТЕЛА, НА КОТОРОЕ МОЖНО СЕСТЬ': 'NOTHING TO LAND ON NEARBY',
  'ПОСАДОЧНЫЙ КОМПЬЮТЕР: ': 'LANDING COMPUTER: ',
  'ДОКИНГ-КОМПЬЮТЕР ОТКЛЮЧЁН': 'DOCKING COMPUTER OFF',
  'СТАНЦИЙ ПОБЛИЗОСТИ НЕТ': 'NO STATIONS NEARBY',
  'ДОКИНГ-КОМПЬЮТЕР: ': 'DOCKING COMPUTER: ',
  'РУЧНОЕ УПРАВЛЕНИЕ': 'MANUAL CONTROL',
  'СИСТЕМА ': 'SYSTEM ',
  'ПРИБЫТИЕ: ': 'ARRIVAL: ',
  'ВЫХОД ИЗ ПРЫЖКА': 'JUMP COMPLETE',
  'ХОД ПОГАШЕН': 'SPEED KILLED',
  'ВАРП ОТМЕНЁН': 'WARP CANCELLED',
  'ПРЫЖОК ОТМЕНЁН': 'JUMP CANCELLED',
  'Столкновение с ': 'Collision with ',
  'ПОСАДКА БЕЗ ШАССИ · −': 'LANDED WITHOUT GEAR · −',
  '% КОРПУСА': '% HULL',
  'ПОСАДКА ВЫПОЛНЕНА: ': 'LANDED: ',
  ' Корпус разрушен.': ' Hull destroyed.',
  'СТЫКОВКА ВЫПОЛНЕНА': 'DOCKED',
  'Удар о конструкции станции ': 'Impact on the structures of station ',
  'ЦЕЛЬ ПРОПАЛА С ЛОКАТОРА · ПРЫЖОК СОРВАН': 'TARGET LOST FROM SCOPE · JUMP ABORTED',
  'СВЯЗЬ С СЕРВЕРОМ ПОТЕРЯНА · АВТОНОМНО': 'SERVER LINK LOST · OFFLINE',
  'СВЯЗЬ ВОССТАНОВЛЕНА': 'LINK RESTORED',
  'ВХОД ПРОСРОЧЕН · СОХРАНЕНИЕ ТОЛЬКО МЕСТНОЕ': 'LOGIN EXPIRED · SAVING LOCALLY ONLY',
  'СЕРВЕР НЕ ОТВЕЧАЕТ · АВТОНОМНЫЙ РЕЖИМ': 'SERVER NOT ANSWERING · OFFLINE MODE',
  'ВИДЕОКАРТА НЕ ЗАДЕЙСТВОВАНА · ПРОГРАММНЫЙ РЕНДЕР': 'GPU NOT IN USE · SOFTWARE RENDERER',
  'ИГРА ИДЁТ НА ВСТРОЕННОЙ ГРАФИКЕ · ': 'RUNNING ON INTEGRATED GRAPHICS · ',
  ' — ЦЕЛЬ: ': ' — TARGET: ',
  'орбитальная станция': 'orbital station',
  'орбитальный маркер': 'orbital marker',
  'звезда': 'star',
  'вулканическая планета': 'volcanic planet',
  'каменистая планета': 'rocky planet',
  'пустынная планета': 'desert planet',
  'океаническая планета': 'ocean planet',
  'ледяная планета': 'ice planet',
  'газовый гигант': 'gas giant',
  'луна': 'moon',
  'СТАНЦИЯ СЛИШКОМ ДАЛЕКО — ПРЫЖОК (B)': 'STATION TOO FAR — JUMP (B)',
  'красный карлик': 'red dwarf',
  'оранжевый карлик': 'orange dwarf',
  'жёлтый карлик': 'yellow dwarf',
  'бело-жёлтая': 'yellow-white',
  'белая': 'white',
  'ШАССИ ВЫПУЩЕНО': 'GEAR DOWN',
  'ВЫПУСК ШАССИ…': 'GEAR EXTENDING…',
  'УБОРКА ШАССИ…': 'GEAR RETRACTING…',
  'ШАССИ УБРАНО': 'GEAR STOWED',
  'СЕСТЬ МОЖНО ТОЛЬКО НА ТЕЛО БЕЗ АТМОСФЕРЫ': 'LANDING IS ONLY POSSIBLE ON AN AIRLESS BODY',
  'ТЕЛО СЛИШКОМ ДАЛЕКО — СНАЧАЛА ПРЫЖОК (B)': 'BODY TOO FAR — JUMP FIRST (B)',
  'подход': 'approach',
  'спуск': 'descent',
  'выравнивание': 'levelling',
  'Столкновение с поверхностью ': 'Collision with the surface of ',
  'Посадка без шасси.': 'Landed without gear.',
  'Касание поверхности без шасси, с перекосом.': 'Touched down without gear, tilted.',
  'Корабль не выровнен по площадке — опрокидывание.': 'Ship not level with the pad — rollover.',
  '/с, до ': '/s, up to ',
  'ЧИСЛА НЕ ЧИТАЮТСЯ': 'DATA UNREADABLE',
  'ГРУНТ': 'GROUND',
  'ГНЕЗДО СВОБОДНО': 'MOUNT EMPTY',
  'МАРШЕВЫЙ ДВИГАТЕЛЬ': 'MAIN ENGINE',
  'ФОРСИРОВАННЫЙ ДВИГАТЕЛЬ': 'UPRATED ENGINE',
  'МАНЕВРОВЫЕ': 'THRUSTERS',
  ' км/с²': ' km/s²',
  'ПОДЪЁМНЫЕ ДВИГАТЕЛИ': 'LIFT ENGINES',
  ' к весу': ' of weight',
  'КВАНТОВЫЙ ПРИВОД': 'QUANTUM DRIVE',
  'ВАРП-ПРИВОД': 'WARP DRIVE',
  'МЕЖСИСТЕМНЫЙ': 'INTERSTELLAR',
  'ДОКИНГ-КОМПЬЮТЕР': 'DOCKING COMPUTER',
  'ЕСТЬ': 'FITTED',
  'ПОСАДОЧНЫЙ КОМПЬЮТЕР': 'LANDING COMPUTER',
  'СКАНЕР': 'SCANNER',
  'ТРЮМ': 'HOLD',
  ' т': ' t',
  'ЩИТЫ': 'SHIELDS',
  ' ед., +': ' u, +',
  '/с через ': '/s after ',
  'НЕТ': 'NONE',
  ' (звезда)': ' (star)',
  ' (луна)': ' (moon)',
  'кр': 'cr',
  'НАЧАЛЬНЫЙ КАПИТАЛ': 'STARTING CAPITAL',
  'СТРАХОВКА КОРПУСА, ВЗНОС': 'HULL INSURANCE, PREMIUM',
  'ПОСТАВКА: ВОДА, 6 Т': 'DELIVERY: WATER, 6 T',
  'ПОСТАВКА: ЗЕРНО, 4 Т': 'DELIVERY: GRAIN, 4 T',
  'СТЫКОВОЧНЫЙ СБОР · LAVE II': 'DOCKING FEE · LAVE II',
  'ВОДА': 'WATER',
  'ЗЕРНО': 'GRAIN',
  'ЖЕЛЕЗНАЯ РУДА': 'IRON ORE',
  'ДОСТАВКА · LAVE VI': 'DELIVERY · LAVE VI',
  'Сдать 4 т зерна на станции газового гиганта. Груз в трюме.': 'Drop 4 t of grain at the gas giant station. Cargo is in the hold.',
  'РАЗВЕДКА · BEON': 'SURVEY · BEON',
  'Снять показания у звезды соседней системы. Нужен варп-прыжок.': 'Take readings at the star of the neighbouring system. Needs a warp jump.',
  'ПРИВОД НЕ РАБОТАЕТ НА СТОЯНКЕ': 'THE DRIVE DOES NOT WORK WHILE PARKED',
  'КОРИДОР ПЕРЕКРЫТ: ': 'CORRIDOR BLOCKED: ',
  'ЦЕЛЬ ВАРПА НЕ ВЫБРАНА: M, ЗАТЕМ G, ЗАТЕМ СИСТЕМУ': 'NO WARP TARGET: M, THEN G, THEN A SYSTEM',
  'ВЫ УЖЕ В ЭТОЙ СИСТЕМЕ': 'YOU ARE ALREADY IN THIS SYSTEM',
  'СНАЧАЛА ОТСТЫКОВКА': 'UNDOCK FIRST',
  'СНАЧАЛА ВЗЛЁТ': 'LIFT OFF FIRST',
  'ЛАЗЕРНАЯ ПУШКА': 'LASER CANNON',
  'КАРДАН': 'GIMBAL',
  'НЕПОДВИЖНАЯ': 'FIXED',
  'РАКЕТНАЯ УСТАНОВКА': 'MISSILE RACK',
  'ТУРЕЛЬ': 'TURRET',
  'КРУГОВАЯ': 'ALL-ROUND',
  ' · ОМ-': ' · OM-',
  'сервер недоступен': 'server unavailable',
  'сервер ответил не по-нашему (': 'the server answered in a language we do not speak (',
  'неизвестная ошибка': 'unknown error',
  'нет связи с сервером': 'no link to the server',

  // --- экраны: порт, крушение, справка -------------------------------------------
  'Счёт': 'Balance',
  'Уровень порта': 'Port tech level',
  'из 5': 'of 5',
  'Сбор за место': 'Berth fee',
  'Услуги': 'Services',
  'Корпус повреждён, а чинить здесь нечем: нужен порт с мастерской.': 'Hull damaged, and there is nothing to fix it with here: you need a port with a workshop.',
  'Корпус цел. Порт свободен для вылета.': 'Hull intact. The port is clear for launch.',
  'Корпус восстановлен. Порт свободен для вылета.': 'Hull restored. The port is clear for launch.',
  'ВЫЛЕТ': 'LAUNCH',
  'РЕМОНТ · ': 'REPAIR · ',
  'КАРТА СИСТЕМЫ': 'SYSTEM MAP',
  'Планета': 'Planet',
  'Тип': 'Type',
  'Радиус планеты': 'Planet radius',
  'Высота орбиты': 'Orbit altitude',
  'Состояние корпуса': 'Hull condition',
  'Стыковок выполнено': 'Dockings made',
  'КОРПУС РАЗРУШЕН': 'HULL DESTROYED',
  'Страховка восстановила корабль на последней станции.': 'Insurance has restored the ship at the last station.',
  'ПРОДОЛЖИТЬ': 'CONTINUE',
  'УПРАВЛЕНИЕ': 'CONTROLS',
  'нос вниз / вверх': 'nose down / up',
  'рыскание влево / вправо': 'yaw left / right',
  'крен влево / вправо': 'roll left / right',
  'крен (схема Elite)': 'roll (Elite scheme)',
  'тяга больше / меньше': 'more / less thrust',
  'Ctrl (долго)': 'Ctrl (held)',
  'задний ход (после остановки)': 'reverse (after a full stop)',
  'тяга в ноль / полная': 'thrust to zero / full',
  'подъёмные движки: тяга вверх / вниз': 'lift engines: thrust up / down',
  'выбрать цель, на которую наведён нос': 'select the target the nose points at',
  'квантовый привод: прыжок к цели / срыв': 'quantum drive: jump to target / abort',
  'варп-привод: прыжок в другую систему': 'warp drive: jump to another system',
  'докинг-компьютер (ближе 120 км)': 'docking computer (closer than 120 km)',
  'шасси: выпуск / уборка': 'gear: extend / retract',
  'посадочный компьютер (тела без атмосферы)': 'landing computer (airless bodies)',
  'кокпит / вид от 3-го лица': 'cockpit / third-person view',
  'ПКМ (зажать)': 'RMB (held)',
  'осмотр: головой в кабине, камерой от 3-го лица': 'look around: with your head in the cockpit, with the camera outside',
  'меню пилота: корабль, груз, задания, финансы': 'pilot menu: ship, cargo, contracts, finances',
  'в меню: 1–4, &larr;/&rarr;, ЛКМ': 'in the menu: 1–4, &larr;/&rarr;, LMB',
  'раздел; I или Esc — закрыть': 'section; I or Esc — close',
  'карта системы': 'system map',
  'на карте: колесо, W/S': 'on the map: wheel, W/S',
  'масштаб': 'zoom',
  'на карте: ЛКМ, &larr;/&rarr;': 'on the map: LMB, &larr;/&rarr;',
  'выбрать объект': 'select an object',
  'на карте: G': 'on the map: G',
  'карта галактики / карта системы': 'galaxy map / system map',
  'на карте: Tab': 'on the map: Tab',
  'назначить выбранное целью (в галактике система становится целью варпа сразу при выборе)': 'set the selection as target (in the galaxy a system becomes the warp target the moment it is selected)',
  'на карте: Пробел / X': 'on the map: Space / X',
  'подъехать к выбранному / сброс вида': 'fly the view to the selection / reset the view',
  'эта справка': 'this help',
  'звук: включить / выключить': 'sound: on / off',
  'громкость тише / громче': 'volume down / up',
  'отладочный оверлей': 'debug overlay',
  'телепорт к цели / смена высоты телепорта': 'teleport to target / change teleport altitude',
  'Space (зажать)': 'Space (held)',
  'форсаж: втрое быстрее, пока есть заряд': 'boost: three times faster while the charge lasts',
  'вылет со станции, рестарт после крушения': 'launch from a station, restart after a crash',
  'на грунте: Space': 'on the ground: Space',
  'коротко — зафиксировать; удержать 3 с — взлёт': 'tap — secure the ship; hold 3 s — lift off',
  'начать заново (дважды: сохранение стирается)': 'start over (twice: the save is erased)',
  'Цели видны на экране сразу. Навести нос на нужную и нажать Tab — она выбрана; под прицелом несколько (планета и её станция) — Tab перебирает только их. Перелёт: выбрать цель, навести на неё нос и держать, нажать B. Привод калибруется три секунды и уходит в прыжок; выход — в 250 км над целью. Прямой коридор часто перекрыт планетой, над которой висишь: тогда привод сам предложит обходную точку (ОМ) и поставит её целью — достаточно нажать B ещё раз.': 'Targets are visible on screen right away. Put the nose on one and press Tab — it is selected; when several sit under the crosshair (a planet and its station), Tab cycles through those only. A trip: select the target, keep the nose on it, press B. The drive calibrates for three seconds and jumps; you come out 250 km above the target. The direct corridor is often blocked by the planet you hover over: then the drive offers a detour point (OM) and sets it as the target — just press B again.',
  'Перелёт в другую систему — варп-привод. Порядок такой: открыть карту (<b>M</b>), переключиться на галактику (<b>G</b>) и выбрать систему — щелчком или <b>&larr;</b>/<b>&rarr;</b>. Выбранная система сразу становится целью варпа. Дальше в полёте <b>J</b>: в кадре появится кольцо, показывающее направление на ту звезду, и его надо совместить с носом. Через четыре секунды удержания корабль рвёт с места и уходит в тоннель на двадцать-тридцать секунд; прервать прыжок нельзя. Выход — прямо у чужой звезды, в четырёх её радиусах.': 'A trip to another system is the warp drive. The order: open the map (<b>M</b>), switch to the galaxy (<b>G</b>) and pick a system — by clicking or with <b>&larr;</b>/<b>&rarr;</b>. The selected system becomes the warp target at once. Then, in flight, <b>J</b>: a ring appears showing the direction to that star, and you have to line the nose up with it. After four seconds of holding, the ship tears away and enters the tunnel for twenty to thirty seconds; the jump cannot be interrupted. You come out right at the other star, four of its radii away.',
  'Старой системы во время прыжка не существует: она выгружается из памяти целиком, а новая собирается под тоннелем. Поэтому тоннель и длится так долго — и поэтому в карточке чужой системы на карте галактики нет состава планет. Что там внутри, известно только по прибытии.': 'The old system does not exist during the jump: it is unloaded from memory whole, and the new one is built under the tunnel. That is why the tunnel lasts so long — and why the card of another system on the galaxy map has no list of planets. What is inside is known only on arrival.',
  'Игра идёт <b>на сервере</b>: состояние корабля, кроны, трюм и подряды хранятся там, а браузер держит только кэш на случай обрыва. Пропала связь — в шапке меню загорается «АВТОНОМНО», полёт продолжается, и накопленное уйдёт на сервер, как только он ответит. Стыковка стоит сбора, ремонт корпуса — денег (кнопка на экране порта), и чинят не везде: нужна станция с мастерской. Играть без сервера вовсе — <b>index.html?offline=1</b>; там же корпус, как раньше, чинится при стыковке даром.': 'The game runs <b>on a server</b>: the state of the ship, the crowns, the hold and the contracts live there, while the browser keeps only a cache in case the link drops. Lost the link — «OFFLINE» lights up in the menu header, the flight goes on, and everything accumulated goes to the server as soon as it answers. Docking costs a fee, hull repair costs money (a button on the port screen), and not every port can do it: you need a station with a workshop. To play without a server at all — <b>index.html?offline=1</b>; there the hull is repaired free on docking, as it used to be.',
  '<b>Другие пилоты</b> видны тремя способами сразу: кораблём в кадре, оранжевым квадратом с именем и расстоянием и отметкой на сканере (рядом с кольцом — их число). Видно только тех, кто в той же звёздной системе.': '<b>Other pilots</b> are shown three ways at once: as a ship in the frame, as an orange square with a name and a distance, and as a mark on the scanner (their number sits next to the ring). You see only those in the same star system.',
  '<b>Бой.</b> <b>Tab</b> берёт в цель то, на что наведён нос, — в том числе чужой корабль. <b>Левая кнопка мыши</b> — огонь. Лазерная пушка стоит <b>на кардане</b>: она сама доворачивает ствол к упреждённой точке — туда, где цель окажется, когда болт долетит. Отметка прицела зелёная, пока кардан дотягивается, и жёлтая, когда он упёрся в предел: тогда доворачивать надо самому. Дальность — 2.5 км, дальше болт гаснет.': '<b>Combat.</b> <b>Tab</b> takes whatever the nose points at as the target — another pilot included. <b>Left mouse button</b> — fire. The laser cannon is <b>on a gimbal</b>: it turns the barrel to the lead point itself — to where the target will be when the bolt arrives. The aim mark is green while the gimbal reaches, and amber when it hits its limit: then you have to turn yourself. Range is 2.5 km, beyond that the bolt dies.',
  'К выбранному пилоту работает и <b>квантовый привод</b> (<b>B</b>): выход — за <b>20 км</b> от него, а не в упор, и с его же ходом, если он летит обычно. Ушёл в прыжок сам — выйдем на нуле: за таким вектором лететь некуда. Пропал с локатора посреди калибровки — прыжок срывается, а не идёт к призраку.': 'The <b>quantum drive</b> (<b>B</b>) works on a selected pilot too: you come out <b>20 km</b> away from him, not in his face, and with his own velocity if he flies normally. If he is in a jump himself, you come out at zero: there is nowhere to go along such a vector. If he drops off the scope mid-calibration, the jump is aborted instead of heading for a ghost.',
  'Первым удар принимает <b>щит</b>. Его не видно вовсе — кроме мига попадания: оболочка вспыхивает по форме корпуса, ярче всего там, куда пришёл луч. Щит отрастает сам через несколько секунд тишины, а вот корпус чинят за деньги в порту. Свои корпус и щит — в левом нижнем углу, чужие — полосками над квадратом пилота.': "The <b>shield</b> takes the hit first. It cannot be seen at all — except for the instant of impact: the shell flashes in the shape of the hull, brightest where the beam landed. The shield grows back on its own after a few seconds of quiet, while the hull is repaired for money at a port. Your own hull and shield are in the bottom left corner, other pilots' — on bars above their square.",
  'Урон считает сервер: попадание видит стрелявший, а корпус и щит меняются только на сервере, и обе стороны узнают о них оттуда. Сбитый корабль восстанавливается в том порту, откуда пилот последний раз уходил, — платы за это пока нет.': 'Damage is settled by the server: the shooter sees the hit, but the hull and the shield change only on the server, and both sides learn about them from there. A destroyed ship is restored at the port the pilot last left — there is no charge for that yet.',
  'В левом верхнем углу — <b>связь</b>: полоски показывают качество, число рядом — задержку до сервера. Появились <b>потери</b> — часть снимков не доходит, и чужие корабли будут дёргаться. Там же видно и обрыв: «СВЯЗЬ ОБОРВАНА» — своя игра при этом продолжается, пропадают только чужие.': 'In the top left corner is the <b>link</b>: the bars show quality, the number next to them the delay to the server. If <b>loss</b> appears, some snapshots are not getting through and other ships will jerk. A break shows there too: «LINK LOST» — your own game goes on, only the others disappear.',
  'Меню пилота (<b>I</b>) открывается только в полёте и мир при этом <b>не останавливает</b>: корабль летит дальше, поэтому в подвале меню всё время висит скорость. Управление на это время глохнет — клавиши разбирает меню. Четыре раздела: <b>корабль</b> (габариты, состояние корпуса, бак, установленные модули), <b>груз</b> (сколько тонн занято и чем), <b>задания</b> (срок и награда) и <b>финансы</b> (лента: сколько пришло и сколько ушло в кронах). Груз и задания пока выданы стартовым набором — брать их будет негде, пока на станциях не появятся рынок и доска.': 'The pilot menu (<b>I</b>) opens only in flight and <b>does not stop</b> the world: the ship keeps flying, which is why the speed sits at the bottom of the menu all the time. The controls go dead meanwhile — the keys are read by the menu. Four sections: <b>ship</b> (dimensions, hull condition, tank, installed modules), <b>cargo</b> (how many tons are taken and by what), <b>contracts</b> (deadline and reward) and <b>finances</b> (a ledger: what came in and what went out, in crowns). Cargo and contracts are handed out as a starting set for now — there will be nowhere to take them until stations get a market and a board.',
  'Карта системы (<b>M</b>) — не картинка, а рабочий план. Масштаб колесом или <b>W</b>/<b>S</b>: от всей системы в кадре до окрестностей одной станции. Выбор — щелчком или <b>&larr;</b>/<b>&rarr;</b> (вид сам подъезжает к выбранному), <b>Tab</b> назначает выбранное целью. Справа — карточка объекта: тип, тяжесть, температура, состав атмосферы, возможность посадки и состояние коридора прыжка. Станцию на обзорном масштабе не видно — она сидит внутри значка своей планеты, к ней надо подъехать.': 'The system map (<b>M</b>) is not a picture but a working chart. Zoom with the wheel or <b>W</b>/<b>S</b>: from the whole system in frame to the surroundings of a single station. Select by clicking or with <b>&larr;</b>/<b>&rarr;</b> (the view flies to the selection itself), <b>Tab</b> makes the selection the target. On the right is the object card: type, gravity, temperature, atmosphere, whether you can land and the state of the jump corridor. A station is invisible at overview scale — it sits inside the icon of its planet, you have to fly closer.',
  'Стыковка: войти в щель порта носом вперёд, скорость ниже 0.28 км/с, крен согласован с вращением станции (зелёные огни сверху).': 'Docking: enter the port slot nose first, speed below 0.28 km/s, roll matched to the rotation of the station (green lights on top).',
  'За бортом идёт пыль — крошка и лёд, по которым только и видно скорость: звёзды для этого слишком далеко. Обычным ходом это еле заметная рябь, на форсаже черта вытягивается втрое и поток превращается в полосы. Ничего не включается отдельно: длина черты — это смаз за время экспозиции, то есть сама скорость.': 'Dust goes past outside — grit and ice, the only thing that shows speed: the stars are far too distant for that. At normal thrust it is a barely visible ripple; on boost the streak stretches threefold and the flow turns into lines. Nothing switches on separately: the length of a streak is the smear over the exposure, that is, the speed itself.',
  'На телефоне управление сенсорное: слева джойстик — он ведёт нос (вниз по экрану — нос вверх, как штурвал на себя), справа ползунок тяги, между ними кнопки — форсаж, крен, подъёмные движки, шасси, цель, прыжок. Палец по свободному месту вертит камеру. Полноэкранного режима на iPhone нет: чтобы убрать адресную строку, добавьте игру на экран «Домой». На ПК полный экран — кнопка с уголками в правом верхнем углу.': 'On a phone the controls are touch: on the left a stick that leads the nose (down the screen — nose up, like a yoke pulled towards you), on the right a thrust slider, buttons between them — boost, roll, lift engines, gear, target, jump. A finger on empty space turns the camera. There is no fullscreen mode on iPhone: to hide the address bar, add the game to the Home screen. On a PC fullscreen is the corner button at the top right.',
  'Вид из кабины — не рамка поверх кадра, а сама кабина: рама фонаря, приборная доска и штурвал. Приборы лежат на её экранах — слева тяга, скорость, форсаж и корпус, по центру радар, справа цель и компас, а на табло по стойкам идут сообщения и состояние приводов. Правая кнопка мыши поворачивает голову, а не облетает корабль: глаз остаётся на месте, кабина поворачивается вокруг. Опустите взгляд — увидите доску целиком и штурвал, который ходит за ручками.': 'The cockpit view is not a frame over the picture but the cockpit itself: canopy frame, dashboard and yoke. The instruments live on its screens — thrust, speed, boost and hull on the left, the radar in the middle, target and compass on the right, while messages and drive states run on the pillar displays. The right mouse button turns your head, it does not orbit the ship: the eye stays in place and the cockpit turns around it. Look down and you will see the whole board and the yoke following the controls.',
  'В центре экрана два знака: прицел — куда смотрит нос, зелёный кружок с усами — куда корабль летит на самом деле. Чем дальше они друг от друга, тем сильнее снос; перечёркнутый знак означает движение назад.': 'There are two marks in the middle of the screen: the crosshair — where the nose points, and the green circle with whiskers — where the ship actually flies. The further apart they are, the stronger the drift; a crossed-out mark means moving backwards.',
  'Скорость — вектор с инерцией: на развороте корабль сносит по старому курсу, торможение требует расстояния. Шасси на управление не влияет — оно только снижает предел скорости: компенсатор высоты держит корабль всегда, и с нейтральными ручками он висит на месте. Удар о грунт вне допусков даёт отскок, кувырок и потерю управления на несколько десятых секунды; корпус при этом теряет тем больше, чем сильнее удар — по квадрату скорости. Корабль гибнет, когда корпуса не осталось.': 'Speed is a vector with inertia: in a turn the ship is carried along the old course, braking takes distance. The gear does not affect handling — it only lowers the speed limit: the altitude compensator always holds the ship, and with neutral controls it hangs in place. A ground impact outside the limits gives a bounce, a tumble and a few tenths of a second without control; the hull loses the more the harder the hit — by the square of the speed. The ship dies when no hull is left.',
  'Сел — игра не останавливается: корабль стоит на стойках, а в приборах появляется кнопка <b>ГОТОВ К ПОСАДКЕ</b>. Короткое нажатие <b>Пробел</b> фиксирует его и глушит движки; взлёт — удержание того же Пробела три секунды, полоса показывает, сколько осталось.': 'Landed — the game does not stop: the ship stands on its legs and a <b>READY TO LAND</b> button appears in the instruments. A short press of <b>Space</b> secures it and shuts the engines down; lift off is holding that same Space for three seconds, the bar shows how much is left.',
  'Посадка: сесть можно на луны и голые планеты — там, где нет атмосферы. Отдельного режима нет: тяга по-прежнему ведёт корабль вдоль носа, а <b>R/F</b> поднимают и опускают его подъёмными движками, так что снижаться брюхом вниз и лететь вперёд можно одновременно. Сам корабль не проседает: снижение задаёт пилот ручкой <b>F</b>. Касаться грунта надо на шасси, брюхом вниз, вертикально не быстрее 30 м/с и с боковой скоростью не выше 25 м/с. Всё это умеет делать посадочный компьютер (<b>L</b>) — он же выбирает ровную площадку.': 'Landing: you can land on moons and bare planets — where there is no atmosphere. There is no separate mode: thrust still leads the ship along its nose, while <b>R/F</b> raise and lower it on the lift engines, so you can descend belly-down and fly forward at the same time. The ship does not sink by itself: the descent is set by the pilot with <b>F</b>. Touch the ground on the gear, belly down, vertically no faster than 30 m/s and with lateral speed no higher than 25 m/s. The landing computer (<b>L</b>) can do all of that — and picks a level pad as well.',
  'У поверхности под кораблём рисуется кольцо на грунте радиусом 30 метров и пунктирная нить до корабля с высотой: по ним видно и реальный масштаб, и точку, куда корабль опустится. Тень от солнца падает на грунт по-настоящему — по расстоянию до неё высота видна сразу.': 'Near the surface a ring 30 metres across is drawn on the ground under the ship, with a dashed thread up to the ship showing the altitude: together they give both the real scale and the point the ship will settle on. The shadow from the sun falls on the ground for real — the distance to it shows the height at a glance.',
  'Гравитационный захват: рядом с телом вокруг прицела появляется рамка приборов — скорость, высота над рельефом, вертикальная и боковая скорость, дистанция до цели, притяжение и посадочные условия. В захвате корабль переносится вместе с телом. Планета уходит по орбите и вращается — корабль идёт с ней, поэтому с нулевой тягой он висит над одной и той же точкой грунта, а не над одной и той же точкой пространства.': 'Gravity capture: next to a body a frame of instruments appears around the crosshair — speed, height above the terrain, vertical and lateral speed, distance to target, gravity and landing conditions. In capture the ship is carried along with the body. The planet moves along its orbit and rotates — the ship goes with it, so at zero thrust it hangs over the same point of ground, not over the same point of space.',
  'НАЗАД': 'BACK',

  // --- каталог тел, компьютеры, стартовый экран ----------------------------------
  'УДАР · −': 'HIT · −',
  'Жёлтый карлик, вокруг которого держится вся система. Сесть некуда, а коридор прыжка он перекрывает чаще любой планеты — обходят его через орбитальные маркеры.': 'A yellow dwarf that holds the whole system together. There is nowhere to land, and it blocks the jump corridor more often than any planet — pilots go around it through orbital markers.',
  'Кора не успевает застыть: близкая звезда разминает планету приливами, и тепло идёт изнутри, а не от света. Воздуха нет, сесть можно — но садиться сюда незачем.': 'The crust never sets: the close star kneads the planet with tides, and the heat comes from inside rather than from the light. There is no air, landing is possible — but there is no reason to.',
  'Голый камень без воздуха и воды. Твёрдый рельеф, честная тяжесть и ровные площадки — лучший полигон для посадки вручную.': 'Bare rock without air or water. Solid terrain, honest gravity and level pads — the best training ground for landing by hand.',
  'Разреженный углекислый воздух и пыль от полюса до полюса. Атмосфера тонкая, но настоящая: на скорости обшивка светится, а сесть без аэродинамического спуска нельзя.': 'Thin carbon dioxide air and dust from pole to pole. The atmosphere is thin but real: at speed the skin glows, and you cannot land without an aerodynamic descent.',
  'Вода, облака и плотный кислородный воздух — единственный обжитой мир системы. Спуск сквозь атмосферу пока не по зубам кораблю: живут здесь на орбитальной станции.': 'Water, clouds and dense oxygen air — the only settled world of the system. A descent through the atmosphere is still beyond this ship: people here live on the orbital station.',
  'CO₂ и H₂O': 'CO₂ and H₂O',
  'Азотно-метановая дымка над вечным льдом. Светит сюда мало, и тепла нет ни снаружи, ни изнутри.': 'Nitrogen-methane haze over eternal ice. Little light reaches here, and there is no heat either outside or within.',
  'Водородный шар без поверхности: садиться не на что, снижение кончается давлением. Держит кольца, луны и самую широкую сферу притяжения в системе.': 'A hydrogen ball with no surface: there is nothing to land on, a descent ends in pressure. It holds rings, moons and the widest sphere of gravity in the system.',
  'Безвоздушный спутник: слабая тяжесть, твёрдый грунт, близко к хозяину. Сюда садятся чаще всего.': 'An airless satellite: weak gravity, solid ground, close to its host. This is where pilots land most often.',
  'ДОКИНГ-КОМПЬЮТЕР: ОБХОД СТАНЦИИ ': 'DOCKING COMPUTER: ROUNDING THE STATION ',
  'ДОКИНГ-КОМПЬЮТЕР: ПОДХОД К СТВОРУ ': 'DOCKING COMPUTER: APPROACHING THE SLOT ',
  'ДОКИНГ-КОМПЬЮТЕР: ВЫРАВНИВАНИЕ, снос ': 'DOCKING COMPUTER: LINING UP, drift ',
  ' м, крен ': ' m, roll ',
  'ДОКИНГ-КОМПЬЮТЕР: ВХОД ': 'DOCKING COMPUTER: ENTERING ',
  ' м, снос ': ' m, drift ',
  'ПОСАДКА: ПОДХОД, высота ': 'LANDING: APPROACH, altitude ',
  ', до площадки ': ', to pad ',
  'ПОСАДКА: СПУСК, высота ': 'LANDING: DESCENT, altitude ',
  ', вертикальная ': ', vertical ',
  'ПОСАДКА: ВЫРАВНИВАНИЕ, снос ': 'LANDING: LEVELLING, drift ',
  ', рассогласование ': ', misalignment ',
  'Уклон площадки ': 'Pad slope ',
  '° — шасси не держит.': '° — the gear cannot hold.',
  'Жёсткое касание: ': 'Hard touchdown: ',
  ' м/с.': ' m/s.',
  'Удар корпусом: ': 'Hull impact: ',
  'WebGL2 недоступен': 'WebGL2 unavailable',
  'контекст WebGL потерян': 'WebGL context lost',
  'сокет не открылся': 'socket did not open',
  'обрыв связи': 'link dropped',
  'Корпус повреждён на ': 'Hull damaged by ',
  '%. Ремонт здесь — ': '%. Repair here costs ',
  ' кр.': ' cr.',
  'космический симулятор, система Lave': 'space simulator, the Lave system',
  '— тангаж (нос вниз/вверх),': '— pitch (nose down/up),',
  '— рыскание': '— yaw',
  '— крен (или': '— roll (or',
  '— тяга,': '— thrust,',
  '— стоп,': '— stop,',
  '— полная': '— full',
  '— подъёмные движки: вверх / вниз': '— lift engines: up / down',
  '(зажать) — форсаж': '(held) — boost',
  '— выбрать цель под прицелом,': '— select the target under the crosshair,',
  '— квантовый прыжок к ней': '— quantum jump to it',
  '— докинг-компьютер,': '— docking computer,',
  '— шасси,': '— gear,',
  '— посадка': '— landing',
  '— меню пилота (корабль, груз, задания, финансы)': '— pilot menu (ship, cargo, contracts, finances)',
  '— вид от 3-го лица,': '— third-person view,',
  '— карта,': '— map,',
  '— помощь': '— help',
  '— звук вкл/выкл,': '— sound on/off,',
  '— громкость': '— volume',
  'Перелёт: навести нос на цель и нажать': 'A trip: put the nose on the target and press',
  ', затем держать нос на ней и нажать': ', then keep the nose on it and press',
  '. Привод калибруется три секунды и уходит в прыжок, выход — в 250 км над целью. Если планета перекрыла коридор, привод сам предложит обходную точку.': '. The drive calibrates for three seconds and jumps, coming out 250 km above the target. If a planet blocks the corridor, the drive offers a detour point itself.',
  'На телефоне: слева джойстик — ведёт нос, справа ползунок тяги, между ними кнопки. Палец по свободному месту вертит камеру. Чтобы убрать адресную строку — «Поделиться» → «На экран Домой».': 'On a phone: a stick on the left leads the nose, a thrust slider on the right, buttons between them. A finger on empty space turns the camera. To hide the address bar — «Share» → «Add to Home Screen».',
  'ВО ВЕСЬ ЭКРАН': 'FULLSCREEN',
  'ФОРС': 'BOOST',
  'ШАС': 'GEAR',
  'ПРЫЖ': 'JUMP',
  'ВИД': 'VIEW',
  'КАРТА': 'MAP',
  'ПОСАД': 'LAND',
  // Загрузчик: характеристики корабля приходят из бэкенда (js/boot.js).
  'ХАРАКТЕРИСТИКИ КОРАБЛЯ НЕ ЗАГРУЖЕНЫ: ': 'SHIP SPECIFICATIONS NOT LOADED: ',
  'Поднимите сервер или соберите слепок: ': 'Start the server or build the snapshot: ',
  'характеристики взяты из слепка: ': 'specifications taken from the snapshot: ',
  'характеристики пусты: нечем собрать корабль': 'specifications are empty: nothing to build a ship from',
  'слепок характеристик не читается: ': 'specification snapshot unreadable: ',
};
